### ISSUE TITLE
Schema: how to make label attribute required

### ISSUE THREAD

**Issue by addisonklinke** [diffgram/diffgram#1057]
When defining a new schema, is it possible to make a label attribute required? In the sense that an annotator cannot mark a task as complete unless they've specified the attribute for each labeled region. 

Currently I cannot find an option for this in UI schema editor. Also, I am able to submit annotations with missing attributes which leads me to believe the default behavior is that attributes are optional (the opposite of my desired setup)

**Comment by vitalii-bulyzhyn** [comment]
Hey @addisonklinke 

For now, we don't support required attributes on Diffgram

**Comment by addisonklinke** [comment]
Would it take a lot of changes to support? Having that option is pretty critical for the labeling setup I need to create

**Comment by vitalii-bulyzhyn** [comment]
For now, our team has some critical features in the pipeline, so most likely we won't be able to preoritize it. 

But we are always open for PRs from external contributors

**Comment by addisonklinke** [comment]
I could give it a go if you have some pointers on the general design approach to take. I've just started exploring the project, so I don't have a natural sense for where it would fit in the code base

**Comment by vitalii-bulyzhyn** [comment]
Sure are some docs that may help:

- [dev install](https://diffgram.readme.io/docs/install)
- [contribution guide](https://diffgram.readme.io/docs/developer-contribution-guide)
- [overall architecture](https://diffgram.readme.io/docs/diffgram-architecture) 
- [tasks](https://diffgram.readme.io/docs/tasks-introduction)

**Comment by addisonklinke** [comment]
@vitalii-bulyzhyn I tried setting up the dev install today. The install script accepts my S3 credentials and I requested the RabbitMQ service since I'd like to try some custom workflows. Docker Compose ends with an error though 

```
diffgram-db-1             | 2022-09-27 03:57:09.938 UTC [40] FATAL:  role "root" does not exist
diffgram-db_migration-1   | Error loading secrets: 
diffgram-db_migration-1   | No module named 'shared.settings.secrets'
diffgram-db_migration-1   | Traceback (most recent call last):
diffgram-db_migration-1   |   File "/usr/local/bin/alembic", line 8, in <module>
diffgram-db_migration-1   |     sys.exit(main())
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 577, in main
diffgram-db_migration-1   |     CommandLine(prog=prog).main(argv=argv)
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 571, in main
diffgram-db_migration-1   |     self.run_cmd(cfg, options)
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/config.py", line 551, in run_cmd
diffgram-db_migration-1   |     **dict((k, getattr(options, k, None)) for k in kwarg)
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
diffgram-db_migration-1   |     script.run_env()
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
diffgram-db_migration-1   |     util.load_python_file(self.dir, "env.py")
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
diffgram-db_migration-1   |     module = load_module_py(module_id, path)
diffgram-db_migration-1   |   File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
diffgram-db_migration-1   |     spec.loader.exec_module(module)
diffgram-db_migration-1   |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
diffgram-db_migration-1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
diffgram-db_migration-1   |   File "alembic/env.py", line 6, in <module>
diffgram-db_migration-1   |     from shared.settings import settings
diffgram-db_migration-1   |   File "/app/shared/settings/settings.py", line 186, in <module>
diffgram-db_migration-1   |     RABBITMQ_PORT = int(os.getenv('RABBITMQ_PORT', 5672))
diffgram-db_migration-1   | ValueError: invalid literal for int() with base 10: ''
diffgram-db_migration-1 exited with code 1
service "db_migration" didn't completed successfully: exit 1
```

**Comment by PJEstrada** [comment]
The int(os.getenv('RABBITMQ_PORT))

Env variable seems to be empty. Please set it to the value of your Rabbit service port or to None so that it can grab the default value.
