### ISSUE TITLE
getting started -- docker noob

### ISSUE THREAD

**Issue by SB2020-eye** [diffgram/diffgram#124]
Hi. I have what I imagine is a very basic question for many/all of you reading this.

I am on Windows 10. I have WSL2 running, using Ubuntu 18.04. I installed Docker and made sure of the appropriate WSL2-related settings.

However, I'm not sure what to do next! Lol. Where do I paste the code you give for installing, found on the README page?

Any help would be so appreciated. I've searched and am coming up empty + confused.

**Comment by PJEstrada** [comment]
Hey @SB2020-eye,

Thanks for trying Diffgram out, For sure!

The commands below for the basic/quick installation:
```

git clone https://github.com/diffgram/diffgram.git
cd diffgram
pip install -r requirements.txt
python install.py
# Follow the installer instruction and 
# After install:  View the Web UI at: http://localhost:8085
```

You have to copy and paste them on a CMD shell on your Operating System. You only need to make sure you have python3 and docker compose installed on your machine.

This video might also help you out: https://www.youtube.com/watch?v=y0LE7QPXxE0

Also, If you want to test the UI out without any installation you can just go to https://diffgram.com/ and register an account.

**Comment by SB2020-eye** [comment]
Thank you so much!!!

Now I get this:
```
←[92mWelcome To the Diffgram Installer.←[0m


←[96mFirst We need to know what static storage provider you will use: ←[0m
1. Google Cloud Storage (GCP)
2. Amazon Web Services S3 (AWS S3)
3. Microsoft Azure Storage (Azure)
←[96mEnter 1, 2 or 3. Or write exit to quit the installation: ←[0m2
←[96mPlease provide the AWS Access Key ID: ←[0mc94e002b-b549-4480-91a0-7cb3c96acc4c
←[96mPlease provide the AWS Access Key Secret: ←[0m
←[93mPlease a enter a valid value.←[0m
←[96mPlease provide the AWS Access Key Secret: ←[0mDiffgramkey
←[96mPlease provide the AWS S3 Bucket Name [Default is diffgram-storage]: ←[0mDiffgram
←[96mEnter diffgram version: [Or Press Enter to Get The Latest Version]: ←[0m
←[96mDo you want to use the local database? Y/N [Press Enter to use Local DB]: ←[0mY
←[94mGenerating Environment Variables file...←[0m
←[92m✓ Environment file written to: C:\Users\Scott\diffgram\.env←[0m
Launching Diffgram...
The system cannot find the path specified.
WARNING: The CLOUD_STORAGE_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The ML__CLOUD_STORAGE_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The DIFFGRAM_AZURE_CONNECTION_STRING variable is not set. Defaulting to a blank string.
WARNING: The DIFFGRAM_AZURE_CONTAINER_NAME variable is not set. Defaulting to a blank string.
WARNING: The ML__DIFFGRAM_AZURE_CONTAINER_NAME variable is not set. Defaulting to a blank string.
WARNING: The MAILGUN_KEY variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[624] Failed to execute script docker-compose
✓ Diffgram Successfully Launched!
View the Web UI at: http://localhost:8085
```
Any suggestions? I would appreciate it.

**Comment by PJEstrada** [comment]
This seems to be a docker error: can you double check if you docker service is running? Also running with sudo could do the trick

More info on this error:
https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version
https://github.com/coursera/courseraresearchexports/issues/33

**Comment by SB2020-eye** [comment]
Check that the program (docker) is running? Oh yeah! Right!

That was the issue. Sorry for the trouble. :)

**Comment by PJEstrada** [comment]
No worries glad you got it working :) let us know any other feedback or ideas you have to make the project better
