### ISSUE TITLE
Minio Endpoint is used eventhough AWS is selected during install.py execution

### ISSUE THREAD

**Issue by EnJunChoong** [diffgram/diffgram#1319]
Greetings fellow respected maintainers, 

When running install.py, connection test for AWS will always fail. 

This is because self.use_docker_minio is default to True, but upon choosing AWS as storage provider, the variable is not set to False. Thus, endpoint_url will default to minio_endpoint at "http://localhost:9000"

*Logical block for s3_endpoint_url*
```
    def validate_s3_connection(self):
        if not self.use_docker_minio:
            endpoint_url = self.s3_endpoint_url
        else:
            endpoint_url = 'http://localhost:9000'
```

*Exception for S3 connection while attempting to access minio endpoint instead of AWS S3 endpoint*
```
Testing Connection...
[OK] Connection To S3 Account
[ERROR] Write Permissions
Error Connecting to S3: Please check you have write permissions on the S3 bucket.
Details: Traceback (most recent call last):
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 298, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: Accept-Encoding: identity


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/httpsession.py", line 345, in send
    urllib_response = conn.urlopen(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Users/enjun.choong/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 298, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('Accept-Encoding: identity\r\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 281, in validate_s3_connection
    client.put_object(Body = 'This is a diffgram test file',
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/endpoint.py", line 252, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/endpoint.py", line 199, in _do_get_response
    http_response = self._send(request)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/endpoint.py", line 268, in _send
    return self.http_session.send(request)
  File "/opt/repos/diffgram/env/lib/python3.8/site-packages/botocore/httpsession.py", line 382, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://localhost:9000/driver-onboarding-labelling/diffgram_test_file.txt".
```

We need to set self.use_docker_minio=False before self.validate_s3_connection()

**Comment by PJEstrada** [comment]
Hi @EnJunChoong,

Thanks for pointing this out. We will write a fix for this on next release as it should be something relatively simple.
