### ISSUE TITLE
Query View / Attribute Selector / Not Showing

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1325]
Attributes don't show in the selection box.
Potentially related, selecting an attribute causes search error

```
TypeError: Cannot read properties of null (reading 'replaceAll')
    at 12.73cab3cb61dc13461e46.js:11:56869
    at Array.map (<anonymous>)
    at s.generate_attribute_query (12.73cab3cb61dc13461e46.js:11:56644)
    at s.generate_query (12.73cab3cb61dc13461e46.js:11:55979)
    at s.refresh_query (12.73cab3cb61dc13461e46.js:11:55729)
    at s.attribute_change_event (12.73cab3cb61dc13461e46.js:11:57823)
```

<img src="https://user-images.githubusercontent.com/18080164/220784152-79b16753-e6a3-4269-8e19-71d0225bbd7c.png" width="300" />

<img src="https://user-images.githubusercontent.com/18080164/220784438-8395b9a7-b836-44e5-b72c-053e3f485b78.png" width="300" />

![image](https://user-images.githubusercontent.com/18080164/220784581-38621008-76df-41d3-bf95-09a86dc453e8.png)

**Comment by PJEstrada** [comment]
Thanks for sharing Anthony! Will take a look a this one alongside with the read-only attributes.

**Comment by anthony-sarkis** [comment]
Thanks Pablo! :)

**Comment by PJEstrada** [comment]
I noticed that the attributes created in this project did not have names set yet:

![image](https://user-images.githubusercontent.com/6606958/221023352-45cbfbd3-f140-4bb6-9c99-66529162103d.png)


So after just setting some names the select options re appeared:

![image](https://user-images.githubusercontent.com/6606958/221023505-6e5428a4-27fb-4d41-bfe0-46f5361a6c21.png)


We might still need to set a default name if the string is empty. But for now a workaround would be to just add some name to the attribute.
