### ISSUE TITLE
Error Connecting to S3: Please check you have write permissions on the S3 bucket.

### ISSUE THREAD

**Issue by Danferno** [diffgram/diffgram#1345]
I get `Error Connecting to S3: Please check you have write permissions on the S3 bucket.` after running `python install.py` even though I chose an Azure backend and not an Amazon one.

```
First We need to know what static storage provider you will use:
1. Minio Local Storage [Default]
2. Amazon Web Services S3 (AWS S3)
3. Microsoft Azure Storage (Azure)
4. Google Cloud Storage (GCP)
Enter 1, 2, 3 or 4. Or write exit to quit the installation: 3
Please provide the Azure Connection String: ***
Please provide the Azure Container Name [Default is diffgram-storage]: ml-data
Testing Connection...
[OK] Connection To Azure Account
[OK] Write Permissions
[OK] Read Permissions
Connection to Azure Successful!
Enter diffgram version: [Or Press Enter to Get The Latest Version]:
Do you want to use the local database? Y/N [Press Enter to use Local DB]:
Do Add Z Flag to Postgres Mount? (Use only when using SELinux distros or similar) Y/N [Press Enter to Skip]:
Do you want to add Mailgun to Diffgram?[Y/n]
Do you want to set RabbitMQ Config?
 (default config: localhost:5672 => user - password will be "admin" - "admin"? [Y/n]
Generating Environment Variables file...
✓ Environment file written to: F:\ml-parsing-project\diffgram\diffgram\.env
Launching Diffgram...
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_MINIO_ACCESS_KEY_ID\" variable is not set. Defaulting to a blank string."
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_MINIO_ACCESS_KEY_SECRET\" variable is not set. Defaulting to a blank string."
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_S3_BUCKET_NAME\" variable is not set. Defaulting to a blank string."
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_S3_BUCKET_NAME\" variable is not set. Defaulting to a blank string."
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_MINIO_ACCESS_KEY_ID\" variable is not set. Defaulting to a blank string."
time="2023-04-13T14:49:17+02:00" level=warning msg="The \"DIFFGRAM_MINIO_ACCESS_KEY_SECRET\" variable is not set. Defaulting to a blank string."
[+] Running 10/10
 - Container diffgram-minio-1          Running                                                                                                                                                                                         0.0s
 - Container diffgram-createbuckets-1  Started                                                                                                                                                                                        20.2s
 - Container diffgram-db-1             Healthy                                                                                                                                                                                        53.4s
 - Container rabbitmq                  Healthy                                                                                                                                                                                        53.4s
 - Container diffgram-db_migration-1   Exited                                                                                                                                                                                         46.0s
 - Container diffgram-default-1        Started                                                                                                                                                                                        46.2s
 - Container diffgram-eventhandlers-1  Started                                                                                                                                                                                        46.6s
 - Container diffgram-walrus-1         Started                                                                                                                                                                                        46.6s
 - Container diffgram-frontend-1       Started                                                                                                                                                                                        45.7s
 - Container diffgram-dispatcher-1     Started                                                                                                                                                                                        45.7s
✓ Diffgram Successfully Launched!
View the Web UI at: http://localhost:8085
AAAA True
Testing Connection...
[OK] Connection To S3 Account
[ERROR] Write Permissions
Error Connecting to S3: Please check you have write permissions on the S3 bucket.
Details: Traceback (most recent call last):
  File "F:\ml-parsing-project\diffgram\diffgram\install.py", line 281, in validate_s3_connection
    client.put_object(Body = 'This is a diffgram test file',
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\signers.py", line 93, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\signers.py", line 165, in sign
    auth.add_auth(request)
  File "F:\ml-parsing-project\diffgram\.venv\Lib\site-packages\botocore\auth.py", line 378, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by anthony-sarkis** [comment]
Thanks Pablo

**Comment by PJEstrada** [comment]
Hi @Danferno  thanks for sharing this. We've upgraded diffgram with a fix on the install script. Please pull the latest version with git pull and try re running the install script. Feel free to re open if this is still not working

**Comment by opallch** [comment]
Currently I tried to install Diffgram on a machine with the latest script and with the MiniIO Option but still encountered the same S3 Bucket connection error:
```
First We need to know what static storage provider you will use: 
1. Minio Local Storage [Default]
2. Amazon Web Services S3 (AWS S3)
3. Microsoft Azure Storage (Azure)
4. Google Cloud Storage (GCP)
Enter 1, 2, 3 or 4. Or write exit to quit the installation: 
Would you like to provide a custom MinIO host? Default will use docker Y/N?
Please provide the Minio S3 Bucket Name [Default is diffgram-storage]: 
Enter diffgram version: [Or Press Enter to Get The Latest Version]: 

Do you want to use the local database? Y/N [Press Enter to use Local DB]: Do Add Z Flag to Postgres Mount? (Use only when using SELinux distros or similar) Y/N [Press Enter to Skip]: 
Do you want to add Mailgun to Diffgram?[Y/n] 
Do you want to set RabbitMQ Config? 
 (default config: localhost:5672 => user - password will be "admin" - "admin"? [Y/n] 
Generating Environment Variables file...
✓ Environment file written to: /home/anno/diffgram/.env
Launching Diffgram...
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddiffgram%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
✓ Diffgram Successfully Launched!
View the Web UI at: http://localhost:8085
Testing Connection...
[OK] Connection To S3 Account
[ERROR] Write Permissions
Error Connecting to S3: Please check you have write permissions on the S3 bucket.
Details: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 345, in send
    urllib_response = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 92, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 120, in _send_output
    self.send(msg)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/awsrequest.py", line 204, in send
    return super(AWSConnection, self).send(str)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x7facf19f9600>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anno/diffgram/install.py", line 281, in validate_s3_connection
    client.put_object(Body = 'This is a diffgram test file',
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/client.py", line 694, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/client.py", line 714, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 252, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 199, in _do_get_response
    http_response = self._send(request)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/endpoint.py", line 268, in _send
    return self.http_session.send(request)
  File "/home/anno/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 374, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:9000/diffgram-storage/diffgram_test_file.txt"

Please update permissions and try again
```
Thanks in advance!

**Comment by PJEstrada** [comment]
Seem like this is an issue with you docker permissions:

```
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddiffgram%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
```

Please check if you can correctly run `docker compose up` on the project, and try to correct the permissions problem. Won't reopen as it is a different issue from the one on this issue.
