### ISSUE TITLE
default container exit 

### ISSUE THREAD

**Issue by JKYang01** [diffgram/diffgram#1616]
```
[2024-06-18 20:49:12,666] INFO system_startup_checker.py Line 17: [default_service] Performing System Checks...
[2024-06-18 20:49:12,918] INFO system_events.py Line 95: Checking for version upgrades [default_service]
[2024-06-18 20:49:12,926] ERROR system_startup_checker.py Line 25: Traceback (most recent call last):
  File "/app/methods/startup/system_startup_checker.py", line 22, in execute_startup_checks
    client = QueueClient()
             ^^^^^^^^^^^^^
  File "/app/shared/queueclient/QueueClient.py", line 42, in __init__
    self.connection = pika.BlockingConnection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

[2024-06-18 20:49:12,926] ERROR system_startup_checker.py Line 26: Error connecting to rabbit MQ
Traceback (most recent call last):
  File "/app/methods/startup/system_startup_checker.py", line 22, in execute_startup_checks
    client = QueueClient()
             ^^^^^^^^^^^^^
  File "/app/shared/queueclient/QueueClient.py", line 42, in __init__
    self.connection = pika.BlockingConnection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 141, in <module>
    startup_checker.execute_startup_checks()
  File "/app/methods/startup/system_startup_checker.py", line 27, in execute_startup_checks
    raise (Exception('Error connecting to RabbitMQ'))
Exception: Error connecting to RabbitMQ
```
here is the information of my rabbitMQ setting:
RABBITMQ_DEFAULT_USER=admin
RABBITMQ_DEFAULT_PASS=admin
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672 
I just set it as default

**Comment by anthony-chaudhary** [comment]
@JKYang01 please verify rabbitMQ is running?

**Comment by JKYang01** [comment]
Thank you for your reply, I rebuilt the whole container and seems it is good now.

**Comment by anthony-chaudhary** [comment]
Great!
