### ISSUE TITLE
Max Connection Pool Reached When Importing 200k images on Walrus

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#171]
While importing 200k images,  the process stopped with the following log error on the Walrus service.

![image](https://user-images.githubusercontent.com/73854485/126805273-a6710dfc-40bd-4fdf-8a45-a870fa9391d3.png)

```
Attaching to diffgram_walrus_1
walrus_1      | Exception in thread Thread-83199:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
walrus_1      | 
walrus_1      | Exception in thread Thread-88477:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)

```

_Originally posted by @cvm-int in https://github.com/diffgram/diffgram/issues/160#issuecomment-885720379_

**Comment by PJEstrada** [comment]
Hi @cvm-int,

This is problem looks like a connection pool issue on your DB. The Walrus currently uses up to 8 threads and if all are working for pronlonged times it can take up all default connection.

In release 0.7.8: https://github.com/diffgram/diffgram/releases/tag/0.7.8

We've added the `DATABASE_CONNECTION_POOL_SIZE` to increase the default number of connection available. You can set it on the `.env` file in your diffgram folder and then recreate the containers to get the number of connections up. 

We will work on adding a setting to tweak the number of threads that process images in case you needed less to keep connection pool smaller.

Let me know if this helps!

**Comment by cvm-int** [comment]
Thanks for answering. 
So, I made a pull on my repo but the error seems to keep going on.
```
walrus_1      | Exception in thread Thread-2923:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
walrus_1      | 
walrus_1      | Exception in thread Thread-2933:
walrus_1      | Traceback (most recent call last):
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
walrus_1      |     self.run()
walrus_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
walrus_1      |     self._target(*self._args, **self._kwargs)
walrus_1      |   File "/app/shared/database/event/event.py", line 207, in __new_event_threaded
walrus_1      |     event = Event.new(**event_args)
walrus_1      |   File "/app/shared/database/event/event.py", line 290, in new
walrus_1      |     session.flush()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
walrus_1      |     self._flush(objects)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
walrus_1      |     transaction.rollback(_capture_exception=True)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
walrus_1      |     with_traceback=exc_tb,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
walrus_1      |     raise exception
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
walrus_1      |     flush_context.execute()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
walrus_1      |     rec.execute(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
walrus_1      |     uow,
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 213, in save_obj
walrus_1      |     ) in _organize_states_for_save(base_mapper, states, uowtransaction):
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 374, in _organize_states_for_save
walrus_1      |     base_mapper, uowtransaction, states
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 1602, in _connections_for_states
walrus_1      |     connection = uowtransaction.transaction.connection(base_mapper)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 314, in connection
walrus_1      |     return self._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 421, in _connection_for_bind
walrus_1      |     conn = self._parent._connection_for_bind(bind, execution_options)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
walrus_1      |     conn = bind._contextual_connect()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
walrus_1      |     self._wrap_pool_connect(self.pool.connect, None),
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
walrus_1      |     return fn()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
walrus_1      |     return _ConnectionFairy._checkout(self)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
walrus_1      |     fairy = _ConnectionRecord.checkout(pool)
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
walrus_1      |     rec = pool._do_get()
walrus_1      |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
walrus_1      |     code="3o7r",
walrus_1      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 2 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
```

**Comment by PJEstrada** [comment]
Hi @cvm-int !

Did you change the value of `DATABASE_CONNECTION_POOL_SIZE`, what value did you set it to?

Make sure you check this: https://diffgram.readme.io/docs/open-core-docker-install-cheatsheet

to learn how to setup the variable value correctly

**Comment by cvm-int** [comment]
I followed the cheetsheet steps and set DATABASE_CONNECTION_POOL_SIZE=20 and started ok but then it returned the same error. Now I set DATABASE_CONNECTION_POOL_SIZE=40  and keeps running without the previous error (Thanks!!).

Now the script keeps on going but it returnes error 'Error sending xxx to Diffgram Eventhub'.

```
walrus_1      | [2021-07-23 19:28:09,640] INFO process_media.py Line 158: 135046 Added to queue.
walrus_1      | [2021-07-23 19:28:10,231] INFO process_media.py Line 1939: 135046 ID Write Finished
walrus_1      | [2021-07-23 19:28:10,231] INFO process_media.py Line 1815: 135046 InputID Probably Downloaded
walrus_1      | [2021-07-23 19:28:10,777] ERROR event.py Line 313: Error sending 551256 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:11,099] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-23 19:28:11,184] INFO process_media.py Line 158: 135048 Added to queue.
walrus_1      | comit...
walrus_1      | [2021-07-23 19:28:11,804] INFO process_media.py Line 1939: 135048 ID Write Finished
walrus_1      | [2021-07-23 19:28:11,804] INFO process_media.py Line 1815: 135048 InputID Probably Downloaded
walrus_1      | comit...
walrus_1      | comit...
walrus_1      | write_key must have (<class 'str'>,), got: None
walrus_1      | [2021-07-23 19:28:12,322] ERROR event.py Line 313: Error sending 551257 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:12,646] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-23 19:28:12,730] INFO process_media.py Line 158: 163084 Added to queue.
walrus_1      | [2021-07-23 19:28:13,263] INFO process_media.py Line 1939: 163084 ID Write Finished
walrus_1      | [2021-07-23 19:28:13,263] INFO process_media.py Line 1815: 163084 InputID Probably Downloaded
walrus_1      | [2021-07-23 19:28:13,814] ERROR event.py Line 313: Error sending 551258 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:14,189] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-23 19:28:14,274] INFO process_media.py Line 158: 135049 Added to queue.
walrus_1      | comit...
walrus_1      | [2021-07-23 19:28:14,807] INFO process_media.py Line 1939: 135049 ID Write Finished
walrus_1      | [2021-07-23 19:28:14,807] INFO process_media.py Line 1815: 135049 InputID Probably Downloaded
walrus_1      | comit...
walrus_1      | comit...
walrus_1      | write_key must have (<class 'str'>,), got: None
walrus_1      | [2021-07-23 19:28:15,343] ERROR event.py Line 313: Error sending 551259 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:15,736] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-23 19:28:15,821] INFO process_media.py Line 158: 135052 Added to queue.
walrus_1      | [2021-07-23 19:28:16,399] INFO process_media.py Line 1939: 135052 ID Write Finished
walrus_1      | [2021-07-23 19:28:16,399] INFO process_media.py Line 1815: 135052 InputID Probably Downloaded
walrus_1      | [2021-07-23 19:28:16,904] ERROR event.py Line 313: Error sending 551260 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:17,280] INFO process_media.py Line 110: [Media Queue Heartbeat]
walrus_1      | [2021-07-23 19:28:17,365] INFO process_media.py Line 158: 135050 Added to queue.
walrus_1      | comit...
walrus_1      | [2021-07-23 19:28:17,958] INFO process_media.py Line 1939: 135050 ID Write Finished
walrus_1      | [2021-07-23 19:28:17,959] INFO process_media.py Line 1815: 135050 InputID Probably Downloaded
walrus_1      | comit...
walrus_1      | comit...
walrus_1      | write_key must have (<class 'str'>,), got: None
walrus_1      | [2021-07-23 19:28:18,698] ERROR event.py Line 313: Error sending 551261 to Diffgram Eventhub. Status Code: 
walrus_1      | [2021-07-23 19:28:18,826] INFO process_media.py
```

**Comment by PJEstrada** [comment]
Glad the connection pool error is gone. We'll try to identify ways to reduce the number of connections overall. 

As for the `Error sending to Diffgram Eventhub` for now its should not interfere with your uploads, we'll work on seeing the cause of this error as it's related to one of our external monitoring services and not so much to the upload.

Let me know if you have any other questions, otherwise we can proceed to close this issue

**Comment by cvm-int** [comment]
Ok, thanks for your quick support ⚡. This issue can be closed.

**Comment by PJEstrada** [comment]
Sounds good :) Glad we could help! @cvm-int
