### ISSUE TITLE
install.py Azure Storage AuthenticationFailed

### ISSUE THREAD

**Issue by li195111** [diffgram/diffgram#245]
Thanks for all, I have some opinion here.
When I run the command `python install.py`
1. Enter 3 to select the Azure Storage.
2. Enter the connect string .
3. Enter the blob name -> Default name (diffgram-stroage).
4. Write to Blob failed, because no blob here -> here is never mind I create the blob by my hands.
5. Read from Blob failed and exception return following:
`Exception: Error when accessing presigned URL: Status(403). Error: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:1322947c-201e-000d-08d6-938bd2000000
Time:2021-08-18T02:15:58.4441445Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Wed, 18 Aug 2021 02:16:01 GMT] - Expiry [Mon, 28 Nov 2022 07:36:01 GMT] - Current [Wed, 18 Aug 2021 02:15:58 GMT]</AuthenticationErrorDetail></Error>`

I write the azure blob before and it work fine.
so I check the install.py code at line:145
I saw the code here has `start = datetime.datetime.utcnow(),` this arg, and I check my code was written doesn't have this arg.
I annotate this arg and I work perfectly.

So maybe no this line `start = datetime.datetime.utcnow(),` more better?

**Comment by PJEstrada** [comment]
Hi @li195111 !

Thanks for using diffgram and your suggestions :) 

The code here is tightly coupled because we want to check that the same file that was written is being fetched by the system in that small timeframe. `start = datetime.datetime.utcnow()` is for security purposes, to make sure that the blob is expiring after `expiration_offset = 40368000`.

I would suggest that instead of creating the blob by hand, you add write permissions to you connection string, as otherwise you will have problems uploading files to Diffgram once the system is running.

You can read about connection string and permissions here:

https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

https://docs.microsoft.com/en-us/azure/role-based-access-control/rbac-and-directory-admin-roles

Let me know if this helps you and answers your questions

**Comment by li195111** [comment]
Hi @PJEstrada,

I try It again and got same issue, when I copy the connect string from Azure and paste it to `python install.py`

![image](https://user-images.githubusercontent.com/46022495/131205210-8bef4f31-b067-4018-bb4b-45fd0fcd3553.png)

I got same error.

```Testing Connection...
[OK] Connection To Azure Account
[ERROR] Write Permissions
Error Connecting to Azure: Please check you have write permissions on the Azure container.
Details: Traceback (most recent call last):
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 105, in upload_block_blob
    **kwargs)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 231, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'The specified container does not exist.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 126, in validate_azure_connection
    blob_client.upload_blob('This is a diffgram test file', content_settings = my_content_settings, overwrite=True)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 685, in upload_blob
    return upload_block_blob(**options)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/core/exceptions.py", line 247, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_upload_helpers.py", line 105, in upload_block_blob
    **kwargs)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 231, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/liyue/miniconda/envs/diffgram/lib/python3.7/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.
RequestId:72a3cfce-501e-0009-67bd-9b7e50000000
Time:2021-08-28T03:35:36.5453066Z
ErrorCode:ContainerNotFound
Error:None

Please update permissions and try again
(diffgram) liyue@DESKTOP-S85LFBN:/mnt/d/Programing/Projects/Project.Diffgram/diffgram$
```

could you tell me if I have something wrong?

**Comment by PJEstrada** [comment]
Hi @li195111 

The error that you are showing says:

'The specified container does not exist.'


This means that you either haven't created or misspelled the container name you added as an input on the installation script. Please double check the containaer name exists in your account and try again.

Let me know if this helps!
