### ISSUE TITLE
How do I change the port from the default 8080

### ISSUE THREAD

**Issue by RAbraham** [diffgram/diffgram#577]
Hi,
I'm trying to run diffgram on a local server. I see that some of the services use the port 8080 but that's already used by another service of ours in a docker container. How do I go about changing to another port?

What I tried:
- go to the `docker-compose` and change all ports to `9080`
- change all locations in `.env` to `9080`

but that didnt work

Here is the error I got:
```


 error: HTTPConnectionPool(host='walrus', port=9080): Max retries exceeded with url: /api/walrus/v1/interservice/receive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c2f752da0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
 trace: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen chunked=chunked, File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/usr/local/lib/python3.7/http/client.py", line 1229, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output self.send(msg) File "/usr/local/lib/python3.7/http/client.py", line 956, in send self.connect() File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect conn = self._new_conn() File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn self, "Failed to establish a new connection: %s" % e urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7c2f752da0>: Failed to establish a new connection: [Errno -2] Name or service not known During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2] File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='walrus', port=9080): Max retries exceeded with url: /api/walrus/v1/interservice/receive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c2f752da0>: Failed to establish a new connection: [Errno -2] Name or service not known')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/app/methods/task/task_template/job_launch.py", line 136, in task_template_launch_api task_template_launcher.enqueue_task_template_launch(member_created=member) File "/app/methods/task/task_template/job_launch.py", line 35, in enqueue_task_template_launch self.notify_workers() File "/app/methods/task/task_template/job_launch.py", line 42, in notify_workers service_target = 'walrus') File "/app/shared/regular/regular_methods.py", line 111, in transmit_interservice_request response = requests.post(endpoint, data = json.dumps(data)) File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post return request('post', url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='walrus', port=9080): Max retries exceeded with url: /api/walrus/v1/interservice/receive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c2f752da0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
 server: Please try again later. Contact us if this persists. 
```

**Comment by PJEstrada** [comment]
Hello @RAbraham,

Changing the ports on the docker compose file should be all that you need to do in theory. Can you please share you `docker-compose.yaml` to see what are the changes you made and be able to help you out more?

**Comment by RAbraham** [comment]
Hi @PJEstrada 
Thanks for your quick response. I feel like I've changed one port too many.

My `.env` file(elided):
```
DIFFGRAM_S3_BUCKET_NAME=wd-xxx
DIFFGRAM_S3_BUCKET_REGION=us-east-1
ML__DIFFGRAM_S3_BUCKET_NAME=wd-xxx
SAME_HOST=False
DIFFGRAM_STATIC_STORAGE_PROVIDER=aws
GCP_SERVICE_ACCOUNT_FILE_PATH=/dev/null
FERNET_KEY=b'xx'
USER_PASSWORDS_SECRET=xxx
INTER_SERVICE_SECRET=xxx
SECRET_KEY=xxx
WALRUS_SERVICE_URL_BASE=http://walrus:9080/
DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE=True
DIFFGRAM_INSTALL_FINGERPRINT=xxx
DIFFGRAM_VERSION_TAG=0.11.15
DIFFGRAM_HOST_OS=posix linux 5.4.0-80-generic
POSTGRES_IMAGE=postgres:12.5
DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/diffgram
```

My docker-compose file
```

services:
  dispatcher:
    image: gcr.io/diffgram-open-core/local_dispatcher:latest
    ports:
      - "0.0.0.0:8085:8085"
    expose: [8085]
    depends_on:
      - frontend
      - default
      - walrus
    environment:
      SAME_HOST: ${SAME_HOST}
  frontend:
    image: gcr.io/diffgram-open-core/frontend:${DIFFGRAM_VERSION_TAG}
    ports:
      - "0.0.0.0:8081:80"
    expose: [80]
    depends_on:
      - default

  walrus:
    image: gcr.io/diffgram-open-core/walrus:${DIFFGRAM_VERSION_TAG}
    ports:
      - "0.0.0.0:8082:8082"
    expose: [9080]
    depends_on:
      - db
      - default
    volumes:
      - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIFFGRAM_SYSTEM_MODE: "sandbox"
      DIFFGRAM_STATIC_STORAGE_PROVIDER: ${DIFFGRAM_STATIC_STORAGE_PROVIDER}
      USER_PASSWORDS_SECRET: ${USER_PASSWORDS_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      SERVICE_ACCOUNT_FULL_PATH: "/gcp/gcp-service-account.json"
      GOOGLE_APPLICATION_CREDENTIALS: "/gcp/gcp-service-account.json"
      CLOUD_STORAGE_BUCKET: ${CLOUD_STORAGE_BUCKET}
      ML__CLOUD_STORAGE_BUCKET: ${ML__CLOUD_STORAGE_BUCKET}
      DIFFGRAM_AWS_ACCESS_KEY_ID: ${DIFFGRAM_AWS_ACCESS_KEY_ID}
      DIFFGRAM_AWS_ACCESS_KEY_SECRET: ${DIFFGRAM_AWS_ACCESS_KEY_SECRET}
      DIFFGRAM_S3_BUCKET_NAME: ${DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_S3_BUCKET_REGION: ${DIFFGRAM_S3_BUCKET_REGION}
      ML__DIFFGRAM_S3_BUCKET_NAME: ${ML__DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_AZURE_CONNECTION_STRING: ${DIFFGRAM_AZURE_CONNECTION_STRING}
      DIFFGRAM_AZURE_CONTAINER_NAME: ${DIFFGRAM_AZURE_CONTAINER_NAME}
      ML__DIFFGRAM_AZURE_CONTAINER_NAME: ${ML__DIFFGRAM_AZURE_CONTAINER_NAME}
      MAILGUN_KEY: ${MAILGUN_KEY}
      EMAIL_DOMAIN_NAME: ${EMAIL_DOMAIN_NAME}
      WALRUS_SERVICE_URL_BASE: ${WALRUS_SERVICE_URL_BASE}
      INTER_SERVICE_SECRET: ${INTER_SERVICE_SECRET}
      PYTHONPATH: "/app/"
      DIFFGRAM_INSTALL_FINGERPRINT: ${DIFFGRAM_INSTALL_FINGERPRINT}
      DIFFGRAM_VERSION_TAG: ${DIFFGRAM_VERSION_TAG}
      DIFFGRAM_HOST_OS: ${DIFFGRAM_HOST_OS}
      DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE: ${DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE}
      DIFFGRAM_SERVICE_NAME: ${DIFFGRAM_SERVICE_NAME}
    entrypoint: ["python3", "-u", "/app/main.py"]
  default:
    image: gcr.io/diffgram-open-core/default:${DIFFGRAM_VERSION_TAG}
    ports:
      - "0.0.0.0:9080:9080"
    expose: [9080]
    depends_on:
      - db
    volumes:
      - ${GCP_SERVICE_ACCOUNT_FILE_PATH}:/gcp/gcp-service-account.json
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIFFGRAM_SYSTEM_MODE: "sandbox"
      DIFFGRAM_STATIC_STORAGE_PROVIDER: ${DIFFGRAM_STATIC_STORAGE_PROVIDER}
      USER_PASSWORDS_SECRET: ${USER_PASSWORDS_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      SERVICE_ACCOUNT_FULL_PATH: "/gcp/gcp-service-account.json"
      GOOGLE_APPLICATION_CREDENTIALS: "/gcp/gcp-service-account.json"
      CLOUD_STORAGE_BUCKET: ${CLOUD_STORAGE_BUCKET}
      ML__CLOUD_STORAGE_BUCKET: ${ML__CLOUD_STORAGE_BUCKET}
      DIFFGRAM_AWS_ACCESS_KEY_ID: ${DIFFGRAM_AWS_ACCESS_KEY_ID}
      DIFFGRAM_AWS_ACCESS_KEY_SECRET: ${DIFFGRAM_AWS_ACCESS_KEY_SECRET}
      DIFFGRAM_S3_BUCKET_NAME: ${DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_S3_BUCKET_REGION: ${DIFFGRAM_S3_BUCKET_REGION}
      ML__DIFFGRAM_S3_BUCKET_NAME: ${ML__DIFFGRAM_S3_BUCKET_NAME}
      DIFFGRAM_AZURE_CONNECTION_STRING: ${DIFFGRAM_AZURE_CONNECTION_STRING}
      DIFFGRAM_AZURE_CONTAINER_NAME: ${DIFFGRAM_AZURE_CONTAINER_NAME}
      ML__DIFFGRAM_AZURE_CONTAINER_NAME: ${ML__DIFFGRAM_AZURE_CONTAINER_NAME}
      MAILGUN_KEY: ${MAILGUN_KEY}
      EMAIL_DOMAIN_NAME: ${EMAIL_DOMAIN_NAME}
      WALRUS_SERVICE_URL_BASE: ${WALRUS_SERVICE_URL_BASE}
      INTER_SERVICE_SECRET: ${INTER_SERVICE_SECRET}
      PYTHONPATH: "/app/"
      DIFFGRAM_INSTALL_FINGERPRINT: ${DIFFGRAM_INSTALL_FINGERPRINT}
      DIFFGRAM_VERSION_TAG: ${DIFFGRAM_VERSION_TAG}
      DIFFGRAM_HOST_OS: ${DIFFGRAM_HOST_OS}
      DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE: ${DIFFGRAM_ERROR_SEND_TRACES_IN_RESPONSE}
      DIFFGRAM_SERVICE_NAME: ${DIFFGRAM_SERVICE_NAME}
    command: ["/app/db-init.sh", "db", "python3", "-u", "/app/main.py"]

  db:
    image: ${POSTGRES_IMAGE}
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=diffgram
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  static: {}
```

**Comment by PJEstrada** [comment]
Thanks for sharing! @RAbraham 

Some notes on the services so you can get more context:

- Diffgram is made up of 5 services: (default, walrus, frontend, db, dispatcher). Each of those runs on a different port. So depending on what ports are conflicting you just have to focus on changing the conflicting services ports.

- You don't have to change the `expose:` key on the docker compose as that just exposes the port from the docker container into your host system. You can leave those as they are.

The rules you have to change are the `ports:` rules:
You can read more about it here: https://docs.docker.com/compose/networking/

Basically the syntax tells the following:

`ports: "PORT_TO_MAP_ON_YOUR_MACHINE:PORT_ON_THE_CONTAINER"`

So if you want to change the service that is running on `8080`, which is the `default` service you just have to change that service's `ports:` config to something like:
```
    ports:
      - "0.0.0.0:9080:8080"
```

This means: "Map the service running on 8080 in docker container to port 9080 on my host machine".

Since you just changed the `default` service, there's no need to change any other thing on the `.env` file. So you can return the line:
`WALRUS_SERVICE_URL_BASE=http://walrus:9080/` 

back to how it was before. THis only needs to change if you change the ports of the `walrus` service.

Let me know if this helps :)
