### ISSUE TITLE
Fix hard crash if blob can't load

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#870]
In some cases lifecylcle rules can break a task from rendering properly:

https://diffgram.com/task/99297

Double check if all urls are regenerating correctly and that the error handling does not block the task from being rendered.

**Comment by anthony-sarkis** [comment]
Expanding on the error handling, we want some undefined guards here so even if it does fail and we show "can't load blob right now" it doesn't crash it
(In the archived example it does auto "rehydrate" so it will be accessible later in time)

Here's the current cascading error if the blob can't load. (seems to be only in task context not studio)
```
app.7ad9d85fedec526bcaf1.js:308 TypeError: Cannot read properties of null (reading 'map')
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:110:18389)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at _n.evaluate (app.7ad9d85fedec526bcaf1.js:308:27959)
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:308:29818)
    at s.<anonymous> (app.7ad9d85fedec526bcaf1.js:110:133519)
    at s.e._render (app.7ad9d85fedec526bcaf1.js:308:35429)
    at s.i (app.7ad9d85fedec526bcaf1.js:308:68627)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at new _n (app.7ad9d85fedec526bcaf1.js:308:26737)
    at app.7ad9d85fedec526bcaf1.js:308:68641
We @ app.7ad9d85fedec526bcaf1.js:308
app.7ad9d85fedec526bcaf1.js:110 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at s.add_event_listeners (app.7ad9d85fedec526bcaf1.js:110:46272)
    at s.mounted (app.7ad9d85fedec526bcaf1.js:110:47013)
    at s.mounted (app.7ad9d85fedec526bcaf1.js:110:25465)
    at He (app.7ad9d85fedec526bcaf1.js:308:11341)
    at tn (app.7ad9d85fedec526bcaf1.js:308:25388)
    at Object.insert (app.7ad9d85fedec526bcaf1.js:308:20460)
    at E (app.7ad9d85fedec526bcaf1.js:308:60554)
    at s.__patch__ (app.7ad9d85fedec526bcaf1.js:308:61954)
    at s.e._update (app.7ad9d85fedec526bcaf1.js:308:34467)
    at s.i (app.7ad9d85fedec526bcaf1.js:308:68617)
3app.7ad9d85fedec526bcaf1.js:308 TypeError: Cannot read properties of null (reading 'map')
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:110:18389)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at _n.evaluate (app.7ad9d85fedec526bcaf1.js:308:27959)
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:308:29818)
    at s.<anonymous> (app.7ad9d85fedec526bcaf1.js:110:133519)
    at s.e._render (app.7ad9d85fedec526bcaf1.js:308:35429)
    at s.i (app.7ad9d85fedec526bcaf1.js:308:68627)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at _n.run (app.7ad9d85fedec526bcaf1.js:308:27703)
    at pn (app.7ad9d85fedec526bcaf1.js:308:25811)
We @ app.7ad9d85fedec526bcaf1.js:308
app.7ad9d85fedec526bcaf1.js:110 Uncaught (in promise) TypeError: this.canvas_mouse_tools.reset_transform_with_global_scale is not a function
    at s.on_change_current_task (app.7ad9d85fedec526bcaf1.js:110:115795)
app.7ad9d85fedec526bcaf1.js:308 TypeError: Cannot read properties of null (reading 'map')
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:110:18389)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at _n.evaluate (app.7ad9d85fedec526bcaf1.js:308:27959)
    at s.filtered_instance_type_list (app.7ad9d85fedec526bcaf1.js:308:29818)
    at s.<anonymous> (app.7ad9d85fedec526bcaf1.js:110:133519)
    at s.e._render (app.7ad9d85fedec526bcaf1.js:308:35429)
    at s.i (app.7ad9d85fedec526bcaf1.js:308:68627)
    at _n.get (app.7ad9d85fedec526bcaf1.js:308:26819)
    at _n.run (app.7ad9d85fedec526bcaf1.js:308:27703)
    at pn (app.7ad9d85fedec526bcaf1.js:308:25811)
```

**Comment by anthony-sarkis** [comment]
need to cover all media types not only image
