### ISSUE TITLE
"job_status":"Job must have a label schema"} When Creating a Job From the SDK

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#903]
When calling the `job.new()` function from the SDK users are getting:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaron/register_diffgram_task.py", line 78, in <module>
    job = project.job.new(
  File "/home/aaron/.local/lib/python3.8/site-packages/diffgram/job/job.py", line 242, in new
    self.client.handle_errors(response)
  File "/home/aaron/.local/lib/python3.8/site-packages/diffgram/core/core.py", line 197, in handle_errors
    raise Exception(response.text)
Exception: {"log":{"error":{"job_status":"Job must have a label 
```

**Comment by PJEstrada** [comment]
Please try to upgrade to version 0.7.1, just released.

https://github.com/diffgram/python-sdk/releases/tag/0.7.1


We've added some new core concepts to diffgram. One of theses is the label schema:
https://diffgram.readme.io/docs/label-schema-getting-started

Basically now you have to provide the label_schema_id param to the job.new()  function.

This is support on the SDK version 0.7.1
